export type Platform = 'Instagram' | 'YouTube' | 'X' | 'LinkedIn'

export type Niche =
  | 'comedy'
  | 'dance'
  | 'cooking'
  | 'tech'
  | 'fitness'
  | 'fashion'
  | 'beauty'
  | 'travel'
  | 'education'
  | 'gaming'
  | 'music'
  | 'storytelling'
  | 'lifestyle'
  | 'sports'
  | 'art'

export type AgeGroup = '13-17' | '18-24' | '25-34' | '35-44' | '45+'

export interface Creator {
  id: string
  name: string
  handle: string
  platform: Platform
  niche: Niche
  followers: number
  engagementRate: number
  location: string
  language: string
  audienceAge: AgeGroup
  tone: string[]
  keywords: string[]
  bio: string
}

export const NICHES: Niche[] = [
  'comedy',
  'dance',
  'cooking',
  'tech',
  'fitness',
  'fashion',
  'beauty',
  'travel',
  'education',
  'gaming',
  'music',
  'storytelling',
  'lifestyle',
  'sports',
  'art',
]

export const AGE_GROUPS: AgeGroup[] = ['13-17', '18-24', '25-34', '35-44', '45+']

export const creators: Creator[] = [
  {
    id: 'c01',
    name: 'Aarav Mehta',
    handle: '@aaravcracks',
    platform: 'Instagram',
    niche: 'comedy',
    followers: 1250000,
    engagementRate: 7.8,
    location: 'Mumbai, Maharashtra',
    language: 'Hindi',
    audienceAge: '18-24',
    tone: ['witty', 'relatable', 'urban'],
    keywords: ['sketch', 'reels', 'satire', 'office humor', 'gen z'],
    bio: 'Daily sketch comedy on modern Indian office life and relationships.',
  },
  {
    id: 'c02',
    name: 'Priya Nair',
    handle: '@priyamoves',
    platform: 'Instagram',
    niche: 'dance',
    followers: 890000,
    engagementRate: 9.1,
    location: 'Kochi, Kerala',
    language: 'Malayalam',
    audienceAge: '18-24',
    tone: ['energetic', 'expressive', 'graceful'],
    keywords: ['bollywood', 'classical', 'choreography', 'trending', 'fusion'],
    bio: 'Fusion choreographer blending classical Bharatanatyam with pop beats.',
  },
  {
    id: 'c03',
    name: 'Rohan Iyer',
    handle: '@rohaneats',
    platform: 'YouTube',
    niche: 'cooking',
    followers: 2100000,
    engagementRate: 6.4,
    location: 'Bengaluru, Karnataka',
    language: 'English',
    audienceAge: '25-34',
    tone: ['warm', 'informative', 'homely'],
    keywords: ['street food', 'regional', 'recipes', 'budget', 'south indian'],
    bio: 'Home chef documenting regional Indian recipes with a modern twist.',
  },
  {
    id: 'c04',
    name: 'Sneha Kapoor',
    handle: '@snehatech',
    platform: 'YouTube',
    niche: 'tech',
    followers: 1560000,
    engagementRate: 5.2,
    location: 'Pune, Maharashtra',
    language: 'Hindi',
    audienceAge: '18-24',
    tone: ['analytical', 'clear', 'geeky'],
    keywords: ['gadgets', 'reviews', 'smartphones', 'ai', 'unboxing'],
    bio: 'No-nonsense gadget reviews and AI explainers for Indian buyers.',
  },
  {
    id: 'c05',
    name: 'Vikram Singh',
    handle: '@vikramfit',
    platform: 'Instagram',
    niche: 'fitness',
    followers: 720000,
    engagementRate: 8.3,
    location: 'Delhi',
    language: 'Hindi',
    audienceAge: '25-34',
    tone: ['motivational', 'disciplined', 'intense'],
    keywords: ['calisthenics', 'transformation', 'diet', 'home workout', 'gym'],
    bio: 'Calisthenics coach helping busy professionals get fit at home.',
  },
  {
    id: 'c06',
    name: 'Ananya Rao',
    handle: '@ananyastyle',
    platform: 'Instagram',
    niche: 'fashion',
    followers: 980000,
    engagementRate: 6.9,
    location: 'Hyderabad, Telangana',
    language: 'English',
    audienceAge: '18-24',
    tone: ['chic', 'bold', 'aspirational'],
    keywords: ['thrift', 'styling', 'ethnic', 'sustainable', 'ootd'],
    bio: 'Sustainable fashion stylist mixing thrift finds with ethnic wear.',
  },
  {
    id: 'c07',
    name: 'Ishaan Verma',
    handle: '@ishaanplays',
    platform: 'YouTube',
    niche: 'gaming',
    followers: 3400000,
    engagementRate: 7.1,
    location: 'Noida, Uttar Pradesh',
    language: 'Hindi',
    audienceAge: '13-17',
    tone: ['hyped', 'competitive', 'playful'],
    keywords: ['bgmi', 'esports', 'livestream', 'valorant', 'montage'],
    bio: 'Competitive mobile gamer and streamer with a loud, fun community.',
  },
  {
    id: 'c08',
    name: 'Meera Joshi',
    handle: '@meeraglow',
    platform: 'Instagram',
    niche: 'beauty',
    followers: 640000,
    engagementRate: 8.7,
    location: 'Ahmedabad, Gujarat',
    language: 'Gujarati',
    audienceAge: '18-24',
    tone: ['friendly', 'honest', 'glam'],
    keywords: ['skincare', 'makeup', 'grwm', 'drugstore', 'tutorial'],
    bio: 'Honest skincare and affordable makeup tutorials for Indian skin.',
  },
  {
    id: 'c09',
    name: 'Karan Malhotra',
    handle: '@karanwanders',
    platform: 'YouTube',
    niche: 'travel',
    followers: 1870000,
    engagementRate: 5.9,
    location: 'Manali, Himachal Pradesh',
    language: 'Hindi',
    audienceAge: '25-34',
    tone: ['adventurous', 'calm', 'cinematic'],
    keywords: ['backpacking', 'himalayas', 'budget travel', 'vlog', 'offbeat'],
    bio: 'Solo backpacker uncovering offbeat Himalayan trails on a budget.',
  },
  {
    id: 'c10',
    name: 'Dr. Nikhil Sharma',
    handle: '@nikhilexplains',
    platform: 'YouTube',
    niche: 'education',
    followers: 2650000,
    engagementRate: 6.1,
    location: 'Kota, Rajasthan',
    language: 'Hindi',
    audienceAge: '18-24',
    tone: ['authoritative', 'simple', 'encouraging'],
    keywords: ['physics', 'exam prep', 'science', 'concepts', 'neet'],
    bio: 'Making tough science concepts simple for competitive exam aspirants.',
  },
  {
    id: 'c11',
    name: 'Tara DSouza',
    handle: '@tarasings',
    platform: 'Instagram',
    niche: 'music',
    followers: 1120000,
    engagementRate: 8.0,
    location: 'Goa',
    language: 'English',
    audienceAge: '18-24',
    tone: ['soulful', 'indie', 'dreamy'],
    keywords: ['covers', 'original', 'acoustic', 'indie pop', 'live'],
    bio: 'Indie singer-songwriter posting acoustic covers and originals.',
  },
  {
    id: 'c12',
    name: 'Aditya Ghosh',
    handle: '@adityatells',
    platform: 'Instagram',
    niche: 'storytelling',
    followers: 540000,
    engagementRate: 9.4,
    location: 'Kolkata, West Bengal',
    language: 'Bengali',
    audienceAge: '25-34',
    tone: ['emotional', 'poetic', 'intimate'],
    keywords: ['horror', 'folk tales', 'narration', 'mystery', 'spoken word'],
    bio: 'Bengali folk and horror storyteller with a haunting narration style.',
  },
  {
    id: 'c13',
    name: 'Simran Kaur',
    handle: '@simranlifestyle',
    platform: 'Instagram',
    niche: 'lifestyle',
    followers: 760000,
    engagementRate: 7.2,
    location: 'Chandigarh',
    language: 'Punjabi',
    audienceAge: '25-34',
    tone: ['aesthetic', 'aspirational', 'cozy'],
    keywords: ['home decor', 'routine', 'vlog', 'wellness', 'organization'],
    bio: 'Slow-living vlogger sharing cozy home and daily wellness routines.',
  },
  {
    id: 'c14',
    name: 'Rahul Deshmukh',
    handle: '@rahulsportstalk',
    platform: 'YouTube',
    niche: 'sports',
    followers: 1980000,
    engagementRate: 5.6,
    location: 'Nagpur, Maharashtra',
    language: 'Hindi',
    audienceAge: '25-34',
    tone: ['passionate', 'analytical', 'loud'],
    keywords: ['cricket', 'analysis', 'ipl', 'football', 'match review'],
    bio: 'Cricket-first sports analyst breaking down matches and player form.',
  },
  {
    id: 'c15',
    name: 'Nandini Pillai',
    handle: '@nandinipaints',
    platform: 'Instagram',
    niche: 'art',
    followers: 430000,
    engagementRate: 9.8,
    location: 'Chennai, Tamil Nadu',
    language: 'Tamil',
    audienceAge: '18-24',
    tone: ['calming', 'detailed', 'inspiring'],
    keywords: ['watercolor', 'illustration', 'process', 'doodle', 'timelapse'],
    bio: 'Watercolor artist sharing soothing process reels and illustrations.',
  },
  {
    id: 'c16',
    name: 'Zoya Khan',
    handle: '@zoyacomedy',
    platform: 'Instagram',
    niche: 'comedy',
    followers: 670000,
    engagementRate: 8.9,
    location: 'Lucknow, Uttar Pradesh',
    language: 'Hindi',
    audienceAge: '18-24',
    tone: ['sassy', 'observational', 'quirky'],
    keywords: ['skits', 'family humor', 'relatable', 'desi', 'reels'],
    bio: 'Observational desi comedy about big Indian family chaos.',
  },
  {
    id: 'c17',
    name: 'Dev Patel',
    handle: '@devgrooves',
    platform: 'Instagram',
    niche: 'dance',
    followers: 1340000,
    engagementRate: 7.6,
    location: 'Surat, Gujarat',
    language: 'Gujarati',
    audienceAge: '13-17',
    tone: ['playful', 'high-energy', 'trendy'],
    keywords: ['hiphop', 'trending', 'crew', 'street dance', 'challenge'],
    bio: 'Hip-hop dancer riding every viral challenge with his crew.',
  },
  {
    id: 'c18',
    name: 'Lakshmi Menon',
    handle: '@lakshmikitchen',
    platform: 'Instagram',
    niche: 'cooking',
    followers: 820000,
    engagementRate: 7.9,
    location: 'Madurai, Tamil Nadu',
    language: 'Tamil',
    audienceAge: '35-44',
    tone: ['traditional', 'warm', 'authentic'],
    keywords: ['vegetarian', 'authentic', 'festival', 'grandma recipes', 'tamil'],
    bio: 'Preserving authentic Tamil vegetarian and festival recipes.',
  },
  {
    id: 'c19',
    name: 'Arjun Reddy',
    handle: '@arjunbuilds',
    platform: 'YouTube',
    niche: 'tech',
    followers: 940000,
    engagementRate: 6.7,
    location: 'Hyderabad, Telangana',
    language: 'Telugu',
    audienceAge: '25-34',
    tone: ['practical', 'nerdy', 'candid'],
    keywords: ['coding', 'startups', 'developer', 'ai tools', 'productivity'],
    bio: 'Developer sharing coding tips, AI tools and startup building.',
  },
  {
    id: 'c20',
    name: 'Pooja Bhatt',
    handle: '@poojaflex',
    platform: 'Instagram',
    niche: 'fitness',
    followers: 590000,
    engagementRate: 8.5,
    location: 'Jaipur, Rajasthan',
    language: 'Hindi',
    audienceAge: '25-34',
    tone: ['empowering', 'friendly', 'consistent'],
    keywords: ['yoga', 'womens fitness', 'postpartum', 'flexibility', 'wellness'],
    bio: 'Yoga and womens fitness coach focused on strength and mobility.',
  },
  {
    id: 'c21',
    name: 'Kabir Anand',
    handle: '@kabirfits',
    platform: 'YouTube',
    niche: 'fashion',
    followers: 710000,
    engagementRate: 6.2,
    location: 'Mumbai, Maharashtra',
    language: 'English',
    audienceAge: '25-34',
    tone: ['refined', 'confident', 'editorial'],
    keywords: ['menswear', 'grooming', 'streetwear', 'lookbook', 'sneakers'],
    bio: 'Menswear and grooming guide with an editorial streetwear eye.',
  },
  {
    id: 'c22',
    name: 'Riya Sen',
    handle: '@riyabeautybar',
    platform: 'YouTube',
    niche: 'beauty',
    followers: 1450000,
    engagementRate: 6.6,
    location: 'Kolkata, West Bengal',
    language: 'Bengali',
    audienceAge: '25-34',
    tone: ['glam', 'detailed', 'trustworthy'],
    keywords: ['bridal', 'makeup', 'reviews', 'haircare', 'tutorial'],
    bio: 'Bridal makeup artist and product reviewer for every Indian skin tone.',
  },
  {
    id: 'c23',
    name: 'Manav Gupta',
    handle: '@manavonroad',
    platform: 'Instagram',
    niche: 'travel',
    followers: 680000,
    engagementRate: 7.4,
    location: 'Rishikesh, Uttarakhand',
    language: 'Hindi',
    audienceAge: '18-24',
    tone: ['spontaneous', 'friendly', 'raw'],
    keywords: ['road trip', 'motovlog', 'camping', 'adventure', 'budget'],
    bio: 'Motovlogger chasing road trips and riverside campsites.',
  },
  {
    id: 'c24',
    name: 'Fatima Sheikh',
    handle: '@fatimalearns',
    platform: 'Instagram',
    niche: 'education',
    followers: 510000,
    engagementRate: 8.2,
    location: 'Aligarh, Uttar Pradesh',
    language: 'Urdu',
    audienceAge: '18-24',
    tone: ['encouraging', 'clear', 'friendly'],
    keywords: ['english speaking', 'career', 'study tips', 'vocabulary', 'skills'],
    bio: 'Helping students speak confident English and build career skills.',
  },
  {
    id: 'c25',
    name: 'Sameer Rathore',
    handle: '@sameerbeats',
    platform: 'YouTube',
    niche: 'music',
    followers: 2230000,
    engagementRate: 5.8,
    location: 'Indore, Madhya Pradesh',
    language: 'Hindi',
    audienceAge: '18-24',
    tone: ['edgy', 'expressive', 'streetwise'],
    keywords: ['rap', 'hiphop', 'lyrics', 'freestyle', 'desi hiphop'],
    bio: 'Desi hip-hop artist dropping hard-hitting street anthems.',
  },
  {
    id: 'c26',
    name: 'Ira Bose',
    handle: '@irastories',
    platform: 'Instagram',
    niche: 'storytelling',
    followers: 470000,
    engagementRate: 9.2,
    location: 'Shillong, Meghalaya',
    language: 'English',
    audienceAge: '18-24',
    tone: ['whimsical', 'gentle', 'imaginative'],
    keywords: ['fantasy', 'micro fiction', 'poetry', 'narration', 'audio'],
    bio: 'Micro-fiction and fantasy narration with a whimsical voice.',
  },
  {
    id: 'c27',
    name: 'Yash Thakur',
    handle: '@yashdaily',
    platform: 'Instagram',
    niche: 'lifestyle',
    followers: 1030000,
    engagementRate: 6.8,
    location: 'Mumbai, Maharashtra',
    language: 'Hindi',
    audienceAge: '18-24',
    tone: ['aspirational', 'energetic', 'polished'],
    keywords: ['finance', 'productivity', 'day in life', 'hustle', 'self improvement'],
    bio: 'Day-in-life vlogs mixing hustle, money habits and productivity.',
  },
  {
    id: 'c28',
    name: 'Neha Agarwal',
    handle: '@nehaonground',
    platform: 'Instagram',
    niche: 'sports',
    followers: 460000,
    engagementRate: 8.1,
    location: 'Kanpur, Uttar Pradesh',
    language: 'Hindi',
    audienceAge: '18-24',
    tone: ['gritty', 'inspiring', 'candid'],
    keywords: ['badminton', 'athlete', 'training', 'womens sports', 'grassroots'],
    bio: 'National badminton athlete documenting grassroots training life.',
  },
  {
    id: 'c29',
    name: 'Ravi Kumar',
    handle: '@ravidoodles',
    platform: 'Instagram',
    niche: 'art',
    followers: 380000,
    engagementRate: 9.6,
    location: 'Patna, Bihar',
    language: 'Hindi',
    audienceAge: '13-17',
    tone: ['playful', 'creative', 'wholesome'],
    keywords: ['sketching', 'caricature', 'comics', 'process', 'street art'],
    bio: 'Street sketch artist turning strangers into fun caricatures.',
  },
  {
    id: 'c30',
    name: 'Ayesha Rahman',
    handle: '@ayeshalaughs',
    platform: 'YouTube',
    niche: 'comedy',
    followers: 1720000,
    engagementRate: 6.3,
    location: 'Bengaluru, Karnataka',
    language: 'English',
    audienceAge: '25-34',
    tone: ['dry', 'smart', 'relatable'],
    keywords: ['standup', 'sketch', 'workplace', 'observational', 'longform'],
    bio: 'Stand-up comic with sharp workplace and city-life observations.',
  },
  {
    id: 'c31',
    name: 'Harsh Vardhan',
    handle: '@harshsteps',
    platform: 'Instagram',
    niche: 'dance',
    followers: 560000,
    engagementRate: 8.4,
    location: 'Bhopal, Madhya Pradesh',
    language: 'Hindi',
    audienceAge: '18-24',
    tone: ['smooth', 'passionate', 'romantic'],
    keywords: ['contemporary', 'couple dance', 'wedding', 'choreography', 'sangeet'],
    bio: 'Contemporary and wedding choreographer for dreamy sangeet reels.',
  },
  {
    id: 'c32',
    name: 'Divya Shetty',
    handle: '@divyacooks',
    platform: 'YouTube',
    niche: 'cooking',
    followers: 1290000,
    engagementRate: 6.0,
    location: 'Mangaluru, Karnataka',
    language: 'Kannada',
    audienceAge: '25-34',
    tone: ['cheerful', 'practical', 'homely'],
    keywords: ['coastal', 'seafood', 'quick recipes', 'meal prep', 'healthy'],
    bio: 'Coastal Karnataka cooking with quick, healthy everyday meals.',
  },
  {
    id: 'c33',
    name: 'Aryan Chauhan',
    handle: '@aryangeek',
    platform: 'YouTube',
    niche: 'tech',
    followers: 1680000,
    engagementRate: 5.4,
    location: 'Gurugram, Haryana',
    language: 'Hindi',
    audienceAge: '18-24',
    tone: ['excited', 'thorough', 'friendly'],
    keywords: ['laptops', 'pc build', 'gaming gear', 'reviews', 'benchmarks'],
    bio: 'PC build and laptop reviewer obsessed with price-to-performance.',
  },
  {
    id: 'c34',
    name: 'Kritika Jain',
    handle: '@kritikamoves',
    platform: 'Instagram',
    niche: 'fitness',
    followers: 830000,
    engagementRate: 7.7,
    location: 'Delhi',
    language: 'English',
    audienceAge: '18-24',
    tone: ['bubbly', 'motivational', 'modern'],
    keywords: ['pilates', 'dance workout', 'weight loss', 'nutrition', 'reels'],
    bio: 'Dance-workout and pilates coach making fitness feel like fun.',
  },
  {
    id: 'c35',
    name: 'Imran Qureshi',
    handle: '@imrantrends',
    platform: 'Instagram',
    niche: 'fashion',
    followers: 620000,
    engagementRate: 7.1,
    location: 'Hyderabad, Telangana',
    language: 'Urdu',
    audienceAge: '18-24',
    tone: ['trendy', 'bold', 'expressive'],
    keywords: ['ethnic', 'festive', 'styling', 'kurta', 'accessories'],
    bio: 'Festive and ethnic menswear styling with a bold modern edge.',
  },
  {
    id: 'c36',
    name: 'Sonal Mishra',
    handle: '@sonalskincare',
    platform: 'Instagram',
    niche: 'beauty',
    followers: 540000,
    engagementRate: 8.8,
    location: 'Varanasi, Uttar Pradesh',
    language: 'Hindi',
    audienceAge: '25-34',
    tone: ['calm', 'scientific', 'honest'],
    keywords: ['ayurveda', 'skincare', 'natural', 'diy', 'wellness'],
    bio: 'Blending ayurveda with science for honest natural skincare.',
  },
  {
    id: 'c37',
    name: 'Gaurav Nanda',
    handle: '@gauravtravels',
    platform: 'YouTube',
    niche: 'travel',
    followers: 2540000,
    engagementRate: 5.5,
    location: 'Amritsar, Punjab',
    language: 'Punjabi',
    audienceAge: '25-34',
    tone: ['storytelling', 'foodie', 'warm'],
    keywords: ['food travel', 'culture', 'street food', 'documentary', 'heritage'],
    bio: 'Food-and-culture travel films across Indian heritage towns.',
  },
  {
    id: 'c38',
    name: 'Ritu Saxena',
    handle: '@ritututors',
    platform: 'YouTube',
    niche: 'education',
    followers: 990000,
    engagementRate: 6.9,
    location: 'Lucknow, Uttar Pradesh',
    language: 'Hindi',
    audienceAge: '13-17',
    tone: ['patient', 'friendly', 'clear'],
    keywords: ['maths', 'school', 'concepts', 'cbse', 'problem solving'],
    bio: 'Making school maths click for CBSE students with simple tricks.',
  },
  {
    id: 'c39',
    name: 'Nikhil Menon',
    handle: '@nikhilstrings',
    platform: 'Instagram',
    niche: 'music',
    followers: 450000,
    engagementRate: 9.0,
    location: 'Thiruvananthapuram, Kerala',
    language: 'Malayalam',
    audienceAge: '25-34',
    tone: ['soulful', 'classical', 'meditative'],
    keywords: ['guitar', 'fusion', 'carnatic', 'instrumental', 'covers'],
    bio: 'Guitarist fusing Carnatic ragas with cinematic instrumentals.',
  },
  {
    id: 'c40',
    name: 'Sara Thomas',
    handle: '@saranarrates',
    platform: 'Instagram',
    niche: 'storytelling',
    followers: 610000,
    engagementRate: 8.6,
    location: 'Kochi, Kerala',
    language: 'English',
    audienceAge: '25-34',
    tone: ['thoughtful', 'cinematic', 'emotional'],
    keywords: ['true stories', 'documentary', 'human interest', 'voiceover', 'reels'],
    bio: 'Short documentary-style true stories about everyday Indians.',
  },
  {
    id: 'c41',
    name: 'Rohit Bansal',
    handle: '@rohitdailygrind',
    platform: 'Instagram',
    niche: 'lifestyle',
    followers: 480000,
    engagementRate: 7.9,
    location: 'Jaipur, Rajasthan',
    language: 'Hindi',
    audienceAge: '25-34',
    tone: ['grounded', 'minimal', 'practical'],
    keywords: ['minimalism', 'budgeting', 'routine', 'declutter', 'mindful'],
    bio: 'Minimalist living, mindful money and simple daily systems.',
  },
  {
    id: 'c42',
    name: 'Ananya Das',
    handle: '@ananyaballs',
    platform: 'Instagram',
    niche: 'sports',
    followers: 520000,
    engagementRate: 8.0,
    location: 'Bhubaneswar, Odisha',
    language: 'Odia',
    audienceAge: '13-17',
    tone: ['energetic', 'inspiring', 'youthful'],
    keywords: ['football', 'skills', 'training', 'womens sports', 'freestyle'],
    bio: 'Football freestyler showing skills, drills and match-day energy.',
  },
  {
    id: 'c43',
    name: 'Vivek Nair',
    handle: '@vivekclicks',
    platform: 'Instagram',
    niche: 'art',
    followers: 410000,
    engagementRate: 9.3,
    location: 'Panaji, Goa',
    language: 'English',
    audienceAge: '25-34',
    tone: ['artistic', 'calm', 'detailed'],
    keywords: ['photography', 'editing', 'street', 'presets', 'visual'],
    bio: 'Street photographer sharing moody edits and shooting breakdowns.',
  },
  {
    id: 'c44',
    name: 'Tanvi Desai',
    handle: '@tanvigiggles',
    platform: 'Instagram',
    niche: 'comedy',
    followers: 890000,
    engagementRate: 8.2,
    location: 'Vadodara, Gujarat',
    language: 'Gujarati',
    audienceAge: '18-24',
    tone: ['bubbly', 'relatable', 'sweet'],
    keywords: ['couple comedy', 'skits', 'relatable', 'everyday', 'reels'],
    bio: 'Sweet couple-comedy skits about tiny everyday relationship wars.',
  },
  {
    id: 'c45',
    name: 'Farhan Ali',
    handle: '@farhanflow',
    platform: 'YouTube',
    niche: 'dance',
    followers: 1160000,
    engagementRate: 6.5,
    location: 'Hyderabad, Telangana',
    language: 'Urdu',
    audienceAge: '18-24',
    tone: ['smooth', 'urban', 'confident'],
    keywords: ['bboying', 'tutorial', 'breakdance', 'workshop', 'crew'],
    bio: 'B-boy and breakdance tutor running workshops for young dancers.',
  },
  {
    id: 'c46',
    name: 'Preeti Chawla',
    handle: '@preetiplates',
    platform: 'Instagram',
    niche: 'cooking',
    followers: 700000,
    engagementRate: 8.1,
    location: 'Ludhiana, Punjab',
    language: 'Punjabi',
    audienceAge: '35-44',
    tone: ['hearty', 'warm', 'fun'],
    keywords: ['punjabi', 'comfort food', 'baking', 'festive', 'family'],
    bio: 'Hearty Punjabi comfort food and festive family baking.',
  },
  {
    id: 'c47',
    name: 'Siddharth Roy',
    handle: '@sidcodes',
    platform: 'YouTube',
    niche: 'tech',
    followers: 1240000,
    engagementRate: 6.3,
    location: 'Kolkata, West Bengal',
    language: 'English',
    audienceAge: '18-24',
    tone: ['calm', 'articulate', 'insightful'],
    keywords: ['ai', 'web development', 'career', 'tutorials', 'open source'],
    bio: 'AI and web-dev tutorials plus honest tech career advice.',
  },
  {
    id: 'c48',
    name: 'Megha Reddy',
    handle: '@meghawellness',
    platform: 'Instagram',
    niche: 'fitness',
    followers: 650000,
    engagementRate: 8.6,
    location: 'Visakhapatnam, Andhra Pradesh',
    language: 'Telugu',
    audienceAge: '25-34',
    tone: ['calm', 'holistic', 'supportive'],
    keywords: ['yoga', 'meditation', 'mobility', 'breathwork', 'wellness'],
    bio: 'Holistic wellness coach blending yoga, breathwork and mobility.',
  },
  {
    id: 'c49',
    name: 'Aman Kohli',
    handle: '@amanreacts',
    platform: 'YouTube',
    niche: 'gaming',
    followers: 2870000,
    engagementRate: 6.8,
    location: 'Delhi',
    language: 'Hindi',
    audienceAge: '13-17',
    tone: ['hyped', 'funny', 'loud'],
    keywords: ['minecraft', 'reactions', 'livestream', 'gta', 'challenges'],
    bio: 'High-energy gaming reactions, challenges and daily livestreams.',
  },
  {
    id: 'c50',
    name: 'Ishita Banerjee',
    handle: '@ishitaverse',
    platform: 'Instagram',
    niche: 'storytelling',
    followers: 720000,
    engagementRate: 8.9,
    location: 'Kolkata, West Bengal',
    language: 'Bengali',
    audienceAge: '18-24',
    tone: ['dreamy', 'poetic', 'nostalgic'],
    keywords: ['poetry', 'shayari', 'love', 'spoken word', 'nostalgia'],
    bio: 'Bengali-English poetry and shayari on love, loss and nostalgia.',
  },
]
